# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Site Settings
locale                   : "en-US"
title                    : "Your Name"
title_separator          : "-"
name                     : &name "Your Name"
description              : &description "Your Professional Description"
url                      : https://pbombard.github.io
baseurl                  : ""
repository               : "pbombard/pbombard.github.io"
teaser                   :
breadcrumbs              : false
words_per_minute         : 160

# Site Author
author:
  name             : "Your Name"
  avatar           : "/images/profile.jpg"
  bio              : "Your bio goes here"
  location         : "Your Location"
  email            : "your.email@example.com"
  github           : "pbombard"
  linkedin         :
  twitter          :
  googlescholar    :

# Reading Files
include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/New_York

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Theme
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "default"
